version: '3.8'
services:
  ewm:
    build: ewm #название папки/модуля в корневой директории, где докерфайлы лежат
    image: ewm7777 #какое дадим название образу
    container_name: ewm7777 #какое дадим название контейнеру
    ports:
      - "8080:8080"
    environment:
      - EXPLOREWITHME_SERVER_URL=http://statsserver5:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  server:
    build: stats/server
    image: statsserver5
    container_name: statsserver5
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  db:
    image: postgres:13.7-alpine
    container_name: dbStats
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm